cat > chants/valmiki-opening.json << 'EOF'
{
  "id": "valmiki-opening",
  "title": "Valmiki Ramayana — Opening Shloka",
  "tradition": "Ramayana",
  "source": "Valmiki Ramayana, Balakanda 1.1",
  "sanskrit": "तपःस्वाध्यायनिरतं तपस्वी वाग्विदां वरम्\nनारदं परिपप्रच्छ वाल्मीकिर्मुनिपुङ्गवम्",
  "meaning": "Valmiki, the greatest of sages, approached Narada — a master of words, devoted to austerity and sacred study — and asked him a question. This is the moment the Ramayana begins.",
  "syllables": [
    { "text": "TA", "phonetic": "ta", "emphasis": true, "duration": 1 },
    { "text": "pah", "phonetic": "pah", "emphasis": false, "duration": 1 },
    { "text": "SVAADH", "phonetic": "svaadh", "emphasis": true, "duration": 2 },
    { "text": "yaay", "phonetic": "yaay", "emphasis": false, "duration": 1 },
    { "text": "NI", "phonetic": "ni", "emphasis": true, "duration": 1 },
    { "text": "ra", "phonetic": "ra", "emphasis": false, "duration": 1 },
    { "text": "tam", "phonetic": "tam", "emphasis": false, "duration": 1 },
    { "text": "ta", "phonetic": "ta", "emphasis": false, "duration": 1 },
    { "text": "PAS", "phonetic": "pas", "emphasis": true, "duration": 1 },
    { "text": "vee", "phonetic": "vee", "emphasis": false, "duration": 1 },
    { "text": "VAAG", "phonetic": "vaag", "emphasis": true, "duration": 2 },
    { "text": "vi", "phonetic": "vi", "emphasis": false, "duration": 1 },
    { "text": "daam", "phonetic": "daam", "emphasis": false, "duration": 1 },
    { "text": "VA", "phonetic": "va", "emphasis": true, "duration": 1 },
    { "text": "ram", "phonetic": "ram", "emphasis": false, "duration": 1 },
    { "text": "NAA", "phonetic": "naa", "emphasis": true, "duration": 2 },
    { "text": "ra", "phonetic": "ra", "emphasis": false, "duration": 1 },
    { "text": "dam", "phonetic": "dam", "emphasis": false, "duration": 1 },
    { "text": "pa", "phonetic": "pa", "emphasis": false, "duration": 1 },
    { "text": "ri", "phonetic": "ri", "emphasis": false, "duration": 1 },
    { "text": "PAP", "phonetic": "pap", "emphasis": true, "duration": 1 },
    { "text": "rachh", "phonetic": "rachh", "emphasis": false, "duration": 1 },
    { "text": "cha", "phonetic": "cha", "emphasis": false, "duration": 1 },
    { "text": "VAAL", "phonetic": "vaal", "emphasis": true, "duration": 2 },
    { "text": "mee", "phonetic": "mee", "emphasis": false, "duration": 1 },
    { "text": "kir", "phonetic": "kir", "emphasis": false, "duration": 1 },
    { "text": "MU", "phonetic": "mu", "emphasis": true, "duration": 1 },
    { "text": "ni", "phonetic": "ni", "emphasis": false, "duration": 1 },
    { "text": "PUN", "phonetic": "pun", "emphasis": true, "duration": 1 },
    { "text": "ga", "phonetic": "ga", "emphasis": false, "duration": 1 },
    { "text": "vam", "phonetic": "vam", "emphasis": false, "duration": 1 }
  ],
  "rounds": 3
}
EOF

cat > chants/mahabharata-invocation.json << 'EOF'
{
  "id": "mahabharata-invocation",
  "title": "Mahabharata — Peace Invocation",
  "tradition": "Mahabharata",
  "source": "Mahabharata, Shanti Parva",
  "sanskrit": "ॐ नमो भगवते वासुदेवाय\nसत्यं ज्ञानमनन्तं ब्रह्म",
  "meaning": "Salutation to the Divine as Vasudeva — the all-pervading. That which is truth, knowledge, and infinite — that is Brahman.",
  "syllables": [
    { "text": "OM", "phonetic": "ohm", "emphasis": true, "duration": 2 },
    { "text": "NA", "phonetic": "na", "emphasis": true, "duration": 1 },
    { "text": "mo", "phonetic": "mo", "emphasis": false, "duration": 1 },
    { "text": "bhag", "phonetic": "bhag", "emphasis": false, "duration": 1 },
    { "text": "a", "phonetic": "a", "emphasis": false, "duration": 1 },
    { "text": "VA", "phonetic": "va", "emphasis": true, "duration": 1 },
    { "text": "te", "phonetic": "te", "emphasis": false, "duration": 1 },
    { "text": "vaa", "phonetic": "vaa", "emphasis": false, "duration": 1 },
    { "text": "su", "phonetic": "su", "emphasis": false, "duration": 1 },
    { "text": "DE", "phonetic": "de", "emphasis": true, "duration": 1 },
    { "text": "vaa", "phonetic": "vaa", "emphasis": false, "duration": 1 },
    { "text": "ya", "phonetic": "ya", "emphasis": false, "duration": 1 },
    { "text": "SAT", "phonetic": "sat", "emphasis": true, "duration": 1 },
    { "text": "yam", "phonetic": "yam", "emphasis": false, "duration": 1 },
    { "text": "JNYAA", "phonetic": "jnyaa", "emphasis": true, "duration": 2 },
    { "text": "nam", "phonetic": "nam", "emphasis": false, "duration": 1 },
    { "text": "a", "phonetic": "a", "emphasis": false, "duration": 1 },
    { "text": "NAN", "phonetic": "nan", "emphasis": true, "duration": 1 },
    { "text": "tam", "phonetic": "tam", "emphasis": false, "duration": 1 },
    { "text": "BRAH", "phonetic": "brah", "emphasis": true, "duration": 2 },
    { "text": "ma", "phonetic": "ma", "emphasis": false, "duration": 1 }
  ],
  "rounds": 108
}
EOF

cat > chants/kalidasa-kumarasambhava.json << 'EOF'
{
  "id": "kalidasa-kumarasambhava",
  "title": "Kumarasambhava — Opening Verse",
  "tradition": "Kavyam",
  "source": "Kalidasa, Kumarasambhava 1.1",
  "sanskrit": "अस्त्युत्तरस्यां दिशि देवतात्मा\nहिमालयो नाम नगाधिराजः",
  "meaning": "In the northern direction there stands a divine soul — the Himalaya, king of mountains. Kalidasa opens his epic of Shiva and Parvati with this image — the sacred mountain as a living being.",
  "syllables": [
    { "text": "AS", "phonetic": "as", "emphasis": true, "duration": 1 },
    { "text": "ty", "phonetic": "ty", "emphasis": false, "duration": 1 },
    { "text": "ut", "phonetic": "ut", "emphasis": false, "duration": 1 },
    { "text": "TAR", "phonetic": "tar", "emphasis": true, "duration": 1 },
    { "text": "as", "phonetic": "as", "emphasis": false, "duration": 1 },
    { "text": "yaam", "phonetic": "yaam", "emphasis": false, "duration": 2 },
    { "text": "DI", "phonetic": "di", "emphasis": true, "duration": 1 },
    { "text": "shi", "phonetic": "shi", "emphasis": false, "duration": 1 },
    { "text": "DE", "phonetic": "de", "emphasis": true, "duration": 1 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "TAAT", "phonetic": "taat", "emphasis": true, "duration": 2 },
    { "text": "maa", "phonetic": "maa", "emphasis": false, "duration": 1 },
    { "text": "hi", "phonetic": "hi", "emphasis": false, "duration": 1 },
    { "text": "MAA", "phonetic": "maa", "emphasis": true, "duration": 2 },
    { "text": "la", "phonetic": "la", "emphasis": false, "duration": 1 },
    { "text": "yo", "phonetic": "yo", "emphasis": false, "duration": 1 },
    { "text": "NAA", "phonetic": "naa", "emphasis": true, "duration": 1 },
    { "text": "ma", "phonetic": "ma", "emphasis": false, "duration": 1 },
    { "text": "na", "phonetic": "na", "emphasis": false, "duration": 1 },
    { "text": "GAADH", "phonetic": "gaadh", "emphasis": true, "duration": 2 },
    { "text": "i", "phonetic": "i", "emphasis": false, "duration": 1 },
    { "text": "RAA", "phonetic": "raa", "emphasis": true, "duration": 2 },
    { "text": "jah", "phonetic": "jah", "emphasis": false, "duration": 1 }
  ],
  "rounds": 3
}
EOF

cat > chants/taittiriya-shanti.json << 'EOF'
{
  "id": "taittiriya-shanti",
  "title": "Taittiriya Upanishad — Shanti Patha",
  "tradition": "Shastram",
  "source": "Taittiriya Upanishad — Peace Invocation",
  "sanskrit": "ॐ सह नाववतु\nसह नौ भुनक्तु\nसह वीर्यं करवावहै\nतेजस्वि नावधीतमस्तु\nमा विद्विषावहै\nॐ शान्तिः शान्तिः शान्तिः",
  "meaning": "May we be protected together. May we be nourished together. May we work with great energy together. May our study be brilliant. May we not dispute with each other. Om — peace, peace, peace.",
  "syllables": [
    { "text": "OM", "phonetic": "ohm", "emphasis": true, "duration": 2 },
    { "text": "SA", "phonetic": "sa", "emphasis": true, "duration": 1 },
    { "text": "ha", "phonetic": "ha", "emphasis": false, "duration": 1 },
    { "text": "NAA", "phonetic": "naa", "emphasis": true, "duration": 2 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "tu", "phonetic": "tu", "emphasis": false, "duration": 1 },
    { "text": "SA", "phonetic": "sa", "emphasis": true, "duration": 1 },
    { "text": "ha", "phonetic": "ha", "emphasis": false, "duration": 1 },
    { "text": "NAU", "phonetic": "nau", "emphasis": true, "duration": 1 },
    { "text": "bhu", "phonetic": "bhu", "emphasis": false, "duration": 1 },
    { "text": "NAK", "phonetic": "nak", "emphasis": true, "duration": 1 },
    { "text": "tu", "phonetic": "tu", "emphasis": false, "duration": 1 },
    { "text": "SA", "phonetic": "sa", "emphasis": true, "duration": 1 },
    { "text": "ha", "phonetic": "ha", "emphasis": false, "duration": 1 },
    { "text": "VEER", "phonetic": "veer", "emphasis": true, "duration": 2 },
    { "text": "yam", "phonetic": "yam", "emphasis": false, "duration": 1 },
    { "text": "ka", "phonetic": "ka", "emphasis": false, "duration": 1 },
    { "text": "ra", "phonetic": "ra", "emphasis": false, "duration": 1 },
    { "text": "VAA", "phonetic": "vaa", "emphasis": true, "duration": 2 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "hai", "phonetic": "hai", "emphasis": false, "duration": 1 },
    { "text": "te", "phonetic": "te", "emphasis": false, "duration": 1 },
    { "text": "JAS", "phonetic": "jas", "emphasis": true, "duration": 1 },
    { "text": "vi", "phonetic": "vi", "emphasis": false, "duration": 1 },
    { "text": "NAA", "phonetic": "naa", "emphasis": true, "duration": 2 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "dhee", "phonetic": "dhee", "emphasis": false, "duration": 1 },
    { "text": "tam", "phonetic": "tam", "emphasis": false, "duration": 1 },
    { "text": "AS", "phonetic": "as", "emphasis": true, "duration": 1 },
    { "text": "tu", "phonetic": "tu", "emphasis": false, "duration": 1 },
    { "text": "maa", "phonetic": "maa", "emphasis": false, "duration": 1 },
    { "text": "vid", "phonetic": "vid", "emphasis": false, "duration": 1 },
    { "text": "vi", "phonetic": "vi", "emphasis": false, "duration": 1 },
    { "text": "SHAA", "phonetic": "shaa", "emphasis": true, "duration": 2 },
    { "text": "va", "phonetic": "va", "emphasis": false, "duration": 1 },
    { "text": "hai", "phonetic": "hai", "emphasis": false, "duration": 1 },
    { "text": "OM", "phonetic": "ohm", "emphasis": true, "duration": 2 },
    { "text": "SHAAN", "phonetic": "shaan", "emphasis": true, "duration": 2 },
    { "text": "tih", "phonetic": "tih", "emphasis": false, "duration": 1 },
    { "text": "SHAAN", "phonetic": "shaan", "emphasis": true, "duration": 2 },
    { "text": "tih", "phonetic": "tih", "emphasis": false, "duration": 1 },
    { "text": "SHAAN", "phonetic": "shaan", "emphasis": true, "duration": 2 },
    { "text": "tih", "phonetic": "tih", "emphasis": false, "duration": 1 }
  ],
  "rounds": 3
}
EOF

cat > chants/jagadodharana.json << 'EOF'
{
  "id": "jagadodharana",
  "title": "Jagadodharana",
  "tradition": "Kannada",
  "source": "Purandaradasa — Haridasa tradition, 15th–16th century",
  "sanskrit": "ಜಗದೋದ್ಧಾರನ ಆಡಿಸಿದಳೆ ಯಶೋದೆ\nಜಗದೋದ್ಧಾರನ",
  "meaning": "Yashoda rocks the upholder of the universe — she cradles the one who sustains all of creation. A devotional composition by Purandaradasa, the father of Carnatic music, celebrating Krishna as a child held by his mother.",
  "syllables": [
    { "text": "JA", "phonetic": "ja", "emphasis": true, "duration": 1 },
    { "text": "ga", "phonetic": "ga", "emphasis": false, "duration": 1 },
    { "text": "DOD", "phonetic": "dod", "emphasis": true, "duration": 1 },
    { "text": "dhaa", "phonetic": "dhaa", "emphasis": false, "duration": 2 },
    { "text": "ra", "phonetic": "ra", "emphasis": false, "duration": 1 },
    { "text": "na", "phonetic": "na", "emphasis": false, "duration": 1 },
    { "text": "AA", "phonetic": "aa", "emphasis": true, "duration": 2 },
    { "text": "di", "phonetic": "di", "emphasis": false, "duration": 1 },
    { "text": "si", "phonetic": "si", "emphasis": false, "duration": 1 },
    { "text": "DA", "phonetic": "da", "emphasis": true, "duration": 1 },
    { "text": "le", "phonetic": "le", "emphasis": false, "duration": 1 },
    { "text": "ya", "phonetic": "ya", "emphasis": false, "duration": 1 },
    { "text": "SHO", "phonetic": "sho", "emphasis": true, "duration": 1 },
    { "text": "de", "phonetic": "de", "emphasis": false, "duration": 1 },
    { "text": "JA", "phonetic": "ja", "emphasis": true, "duration": 1 },
    { "text": "ga", "phonetic": "ga", "emphasis": false, "duration": 1 },
    { "text": "DOD", "phonetic": "dod", "emphasis": true, "duration": 1 },
    { "text": "dhaa", "phonetic": "dhaa", "emphasis": false, "duration": 2 },
    { "text": "ra", "phonetic": "ra", "emphasis": false, "duration": 1 },
    { "text": "na", "phonetic": "na", "emphasis": false, "duration": 1 }
  ],
  "rounds": 3
}
EOF
